# Generated by Django 2.2.3 on 2019-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20190808_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='name_farsi',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
