# Generated by Django 2.2.3 on 2019-08-19 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20190819_1727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0003_items_name_farsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_score', models.FloatField(default=0)),
                ('app_score', models.FloatField(default=0)),
                ('suggest', models.TextField(blank=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_feedback', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
