# Generated by Django 2.2.3 on 2019-08-11 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('car_certificate_number', models.CharField(max_length=20)),
                ('car_name', models.CharField(max_length=50)),
                ('car_palette_two_first', models.CharField(max_length=2)),
                ('car_palette_letter', models.CharField(max_length=1)),
                ('car_palette_three_last', models.CharField(max_length=3)),
                ('car_palette_city_code', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
