# Generated by Django 2.2.3 on 2019-08-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
