# Generated by Django 2.2.3 on 2019-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_drivermodel_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
