# Generated by Django 2.2.3 on 2019-08-17 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_drivermodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drivermodel',
            name='code_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
