# Generated by Django 2.2.3 on 2019-07-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edaritype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
