# Generated by Django 2.2.3 on 2019-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190820_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='data_done',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
