# Generated by Django 2.2.3 on 2019-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190724_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edari',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='EdariType',
        ),
    ]
