# Generated by Django 2.2.3 on 2019-07-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190715_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(max_length=30)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('is_number_confirmed', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('is_number_confirmed', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
