# Generated by Django 2.2.3 on 2019-07-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tegari'),
    ]

    operations = [
        migrations.AddField(
            model_name='edari',
            name='code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khanevar',
            name='code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tegari',
            name='code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
