# Generated by Django 2.2.3 on 2019-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190715_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usernumber',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
