# Generated by Django 2.2.3 on 2019-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190715_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='is_number_confirmed',
        ),
        migrations.RemoveField(
            model_name='usernumber',
            name='is_email_confirmed',
        ),
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
