# Generated by Django 2.2.3 on 2019-07-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190728_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edari',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='khanevar',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tegari',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
