# Generated by Django 2.2.3 on 2019-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190728_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaghaz_moghava', models.IntegerField(default=0)),
                ('shishe', models.IntegerField(default=0)),
            ],
        ),
    ]
