# Generated by Django 2.2.3 on 2019-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ahan_sabok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='ahan_sangin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='alminium_sanati',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='batery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='darb_plastici',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='ehdaye_daroo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='felezat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='khoshk_darham',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='khoshk_tafkik_nashode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='lastik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='location_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='location_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='naan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='parche',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='zarf_alminium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='zayeat_elecronic',
            field=models.IntegerField(default=0),
        ),
    ]
