# Generated by Django 2.2.3 on 2019-08-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190803_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='alminium_sanati',
            new_name='alminium',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='batery',
            new_name='daftar_ketab',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='darb_plastici',
            new_name='khoshk',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ehdaye_daroo',
            new_name='pet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='khoshk_darham',
        ),
        migrations.RemoveField(
            model_name='order',
            name='khoshk_tafkik_nashode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastik',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zarf_alminium',
        ),
    ]
