# Generated by Django 2.2.3 on 2019-08-05 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_khanevar_code_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='edari',
            name='code_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tegari',
            name='code_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='khanevar',
            name='code_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
