# Generated by Django 2.2.3 on 2019-08-07 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190805_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='score',
        ),
        migrations.AddField(
            model_name='order',
            name='bag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='give_back_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
