# Generated by Django 2.2.3 on 2019-08-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190807_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='not confirmed', max_length=20),
        ),
    ]
