# Generated by Django 2.2.3 on 2019-08-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190808_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sayer',
            field=models.IntegerField(default=0),
        ),
    ]
