# Generated by Django 2.2.3 on 2019-08-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_order_sayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='location_y',
            field=models.FloatField(default=0),
        ),
    ]
