# Generated by Django 2.2.3 on 2019-08-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190812_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ahan_sabok',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ahan_sangin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='felezat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kaghaz_moghava',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zayeat_elecronic',
        ),
    ]
