# Generated by Django 2.2.3 on 2019-08-15 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190816_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Order')),
                ('data_done', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('user.order',),
        ),
    ]
